/* tslint:disable */

/**
 * AUTO-GENERATED FILE @ 2020-07-18 11:15:59 - DO NOT EDIT!
 *
 * This file was automatically generated by schemats v.3.0.3
 * $ schemats generate -c postgres://username:password@localhost:55432/users -t note -t comment -s public
 *
 */

export namespace noteFields {
    export type title = string;
    export type description = string | null;
    export type id = number;

}

export interface note {
    title: noteFields.title;
    description: noteFields.description;
    id: noteFields.id;

}

export namespace commentFields {
    export type text = string | null;
    export type description = string | null;
    export type noteId = number | null;
    export type id = number;

}

export interface comment {
    text: commentFields.text;
    description: commentFields.description;
    noteId: commentFields.noteId;
    id: commentFields.id;

}
